name: Laravel

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: test
          
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: root
      DB_PASSWORD: pass
      APP_ENV: testing
      
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./laravel
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
      working-directory: ./laravel
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: ./laravel
    - name: Generate key
      run: php artisan key:generate
      working-directory: ./laravel
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./laravel
    - name: DB Migration
      run: ./artisan migrate
      working-directory: ./laravel
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: ./artisan test
      working-directory: ./laravel
